### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by furusiyya** [aarnaud/conntrack-event-collector#1]
INFO[0000] Starting...  
INFO[0000] Starting conntrack...  
WARN[0000] NOTICE: Netlink socket buffer size has been set to 60000000 bytes. 
FATA[0000] Dial: dial tcp 127.0.0.1:5672: getsockopt: connection refused

**Comment by aarnaud** [comment]
You must run with root or change right for conntrack with `sudo setcap cap_net_admin+ep /usr/sbin/conntrack`

**Comment by furusiyya** [comment]
I have already tried with sudo and changed right for conntrack.

**Comment by furusiyya** [comment]
INFO[0000] Starting...  
INFO[0000] Starting conntrack...  
FATA[0000] Dial: dial tcp 127.0.0.1:5672: getsockopt: connection refused
